spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://database:5432/postgres
    username: postgres
    password: mysecretpassword

  security:
    user:
      name: admin
      password: admin
  jpa:
    show-sql: true
logging:
  level:
    root: info
    org.springframework.security: debug
    org.springframework.data: debug